[package]
name = "mmdb-grpc"
version = "0.2.0"
authors = ["Takeru Sato <type.in.type@gmail.com>"]
edition = "2018"
description = "The gRPC service for the GeoIP database of MaxMind"
documentation = "https://github.com/tkrs/mmdb-grpc"
homepage = "https://github.com/tkrs/mmdb-grpc"
repository = "https://github.com/tkrs/mmdb-grpc.git"
readme = "README.md"
license = "MIT"
keywords = ["maxmind", "geoip"]

[dependencies]
clap = "3.0.0-beta.1"
crossbeam-channel = "0.4"
env_logger = "0.7"
futures = "0.1"
grpcio = "0.5"
grpcio-proto = "0.5"
log = "0.4"
maxminddb = "0.13"
protobuf = "2.14"
signal-hook = "0.1"
spin = "0.5"
cron = "0.6"
chrono = "0.4"

[build-dependencies]
protobuf-build = { version = "0.11", default-features = false }

[[bin]]
name = "mmdb-server"
path = "src/server.rs"

[[bin]]
name = "mmdb-reload"
path = "src/reloader.rs"

[profile.release]
debug = true
lto = true

[[example]]
name = "mmdb-client"
path = "examples/src/client.rs"
