[package]
name = "mmdb-grpc"
version = "0.1.0"
authors = ["Takeru Sato <type.in.type@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
crossbeam-channel = "0.4"
env_logger = "0.7"
futures = "0.1"
grpcio = "0.5"
log = "0.4"
maxminddb = "0.13"
protobuf = "2.14"
signal-hook = "0.1"
spin = "0.5"

[build-dependencies]
protoc-grpcio = "1.2"

[[bin]]
name = "mmdb-server"
path = "src/server.rs"

[[example]]
name = "mmdb-client"
path = "examples/src/client.rs"
