name: Publish contianer image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ~/.cache/sccache
      - uses: mozilla-actions/sccache-action@v0.0.3
      - name: Setup sccache
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >>$GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >>$GITHUB_ENV
      - run: cargo check --tests --workspace --release --verbose
      - if: github.ref_name == 'master'
        run: cargo test --workspace --release --verbose --no-fail-fast -- --nocapture
      - run: cargo build --workspace --release --verbose
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Get the version
        id: get_version
        run: |
          v="${GITHUB_REF##*/}"
          if [[ "$v" == "master" ]]; then
            echo "VERSION=latest" >>$GITHUB_OUTPUT
          else
            echo "VERSION=${v}" >>$GITHUB_OUTPUT
          fi
      - name: mmdb-server push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/server/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/mmdb-server:${{ steps.get_version.outputs.VERSION }}
          push: true
      - name: mmdb-reload push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/reload/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/mmdb-reload:${{ steps.get_version.outputs.VERSION }}
          push: true
