name: release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          override: true
      - name: install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.13
        run: |
          curl -L "$LINK/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
          echo "::add-path::$PWD/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/"
      - name: start sccache
        run: sccache --start-server
      - name: builds
        uses: actions-rs/cargo@v1
        env:
          RUSTC_WRAPPER: sccache
        with:
          command: build
          args: --workspace --release --verbose
      - name: stop sccache
        run: sccache --stop-server
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: get the version
        id: get_version
        run: |
          v="${GITHUB_REF##*/}" 
          if [[ "$v" == "master" ]]; then
            echo ::set-output name=VERSION::latest
          else
            echo ::set-output name=VERSION::${v}
          fi
      - name: build mmdb-server
        run: docker build -f docker/server/Dockerfile -t tkrs/mmdb-server:${{ steps.get_version.outputs.VERSION }} .
      - name: show mmdb-server version
        run: docker run tkrs/mmdb-server:${{ steps.get_version.outputs.VERSION }} --version
      - name: push mmdb-server
        run: docker push tkrs/mmdb-server:${{ steps.get_version.outputs.VERSION }}
      - name: build mmdb-reload image
        run: docker build -f docker/reload/Dockerfile -t tkrs/mmdb-reload:${{ steps.get_version.outputs.VERSION }} .
      - name: show mmdb-reload version
        run: docker run tkrs/mmdb-reload:${{ steps.get_version.outputs.VERSION }} --version
      - name: push mmdb-reload image
        run: docker push tkrs/mmdb-reload:${{ steps.get_version.outputs.VERSION }}
