name: Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git submodule update --init --recursive
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          override: true
      - name: Install sccache
        env:
          SCCACHE_LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.13
        run: |
          curl -L "$SCCACHE_LINK/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
          echo "::add-path::$PWD/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/"
      - name: cache sccache files
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: release-stable-sccache-0213-cache-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            release-stable-sccache-0213-cache-
      - name: show sccache stats
        run: sccache --show-stats
      - name: Set up RUSTC_WRAPPER
        run: echo "::set-env name=RUSTC_WRAPPER::sccache"
      - name: checks
        uses: actions-rs/cargo@v1
        if: github.ref == 'refs/heads/master'
        with:
          command: check
          args: --tests --workspace --release --verbose
      - name: tests
        if: github.ref == 'refs/heads/master'
        uses: actions-rs/cargo@v1
        timeout-minutes: 20
        with:
          command: test
          args: --workspace --release --verbose --no-fail-fast -- --nocapture
      - name: builds
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release --verbose
      - name: mmdb-server push to GitHub Container Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.actor }}/mmdb-server
          dockerfile: docker/server/Dockerfile
          tag_with_ref: true
      - name: mmdb-reload push to GitHub Container Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.actor }}/mmdb-reload
          dockerfile: docker/reload/Dockerfile
          tag_with_ref: true
      - name: mmdb-server push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USER }}/mmdb-server
          dockerfile: docker/server/Dockerfile
          tag_with_ref: true
      - name: mmdb-reload push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USER }}/mmdb-reload
          dockerfile: docker/reload/Dockerfile
          tag_with_ref: true
      - name: mmdb-server push to Quay.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io
          repository: ${{ secrets.QUAY_USER }}/mmdb-server
          dockerfile: docker/server/Dockerfile
          tag_with_ref: true
      - name: mmdb-reload push to DQuay.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io
          repository: ${{ secrets.QUAY_USER }}/mmdb-reload
          dockerfile: docker/reload/Dockerfile
          tag_with_ref: true
